version: '3.8'

services:
  dotnet-api:
    build:
      context: ./dotnet-api
    ports:
      - "5000:80"
    depends_on:
      - python-api

  python-api:
    build:
      context: ./python-api
    ports:
      - "8000:8000"
